#!/bin/sh

# which osascript > /dev/null 2>&1 && osascript -e 'tell application "Emacs" to activate'
# emacsclient -nc "$@"
emacs=/usr/local/Cellar/emacs/HEAD/bin/emacs
emacsclient=/usr/local/Cellar/emacs/HEAD/bin/emacsclient
# emacs=/usr/local/Cellar/emacs/24.3/Emacs.app/Contents/MacOS/Emacs
# emacsclient=/usr/local/Cellar/emacs/24.3/bin/emacsclient
# alternate for running from Emacs
# emacs=/Applications/Emacs4.app/Contents/MacOS/Emacs-x86_64-10.9
# emacsclient=/Applications/Emacs4.app/Contents/MacOS/bin-x86_64-10.9/emacsclient

if $emacsclient -t --socket-name "publishing" "$@" ;then
echo "Daemon not yet started: starting up."
else

$emacs -q --daemon=publishing -l /Users/leotr/.emacs.d/personal/my-ox-latex.el
$emacsclient -t --socket-name "publishing" "$@"
fi
